import os
from dotenv import load_dotenv

load_dotenv()
HOST_APP = os.environ.get("HOST_BE")
# DB
ENGINE_DB = os.environ.get("ENGINE_DB")
NAME_DB = os.environ.get("NAME_DB")
USER_DB = os.environ.get("USER_DB")
PASSWORD_DB = os.environ.get("PASSWORD_DB")
HOST_DB = os.environ.get("HOST_DB")
PORT_DB = os.environ.get("PORT_DB")

# DB - OAuth Token
ENGINE_DB_OAUTH = os.environ.get("ENGINE_DB_OAUTH")
NAME_DB_OAUTH = os.environ.get("NAME_DB_OAUTH")
USER_DB_OAUTH = os.environ.get("USER_DB_OAUTH")
PASSWORD_DB_OAUTH = os.environ.get("PASSWORD_DB_OAUTH")
HOST_DB_OAUTH = os.environ.get("HOST_DB_OAUTH")
PORT_DB_OAUTH = os.environ.get("PORT_DB_OAUTH")

# FPT PRODUCTION
ENGINE_DB_HIS_PRODUCTION_FPT_MSSQL = os.environ.get(
    "ENGINE_DB_HIS_PRODUCTION_FPT_MSSQL")
NAME_DB_HIS_PRODUCTION_FPT_MSSQL = os.environ.get(
    "NAME_DB_HIS_PRODUCTION_FPT_MSSQL")
USER_DB_HIS_PRODUCTION_FPT_MSSQL = os.environ.get(
    "USER_DB_HIS_PRODUCTION_FPT_MSSQL")
PASSWORD_DB_HIS_PRODUCTION_FPT_MSSQL = os.environ.get(
    "PASSWORD_DB_HIS_PRODUCTION_FPT_MSSQL")
HOST_DB_HIS_PRODUCTION_FPT_MSSQL = os.environ.get(
    "HOST_DB_HIS_PRODUCTION_FPT_MSSQL")
PORT_DB_HIS_PRODUCTION_FPT_MSSQL = os.environ.get(
    "PORT_DB_HIS_PRODUCTION_FPT_MSSQL")
CONNECTION_STRING_HIS_PRODUCTION_FPT_MSSQL = f"DRIVER={{ODBC Driver 17 for SQL Server}};SERVER={HOST_DB_HIS_PRODUCTION_FPT_MSSQL};DATABASE={NAME_DB_HIS_PRODUCTION_FPT_MSSQL};UID={USER_DB_HIS_PRODUCTION_FPT_MSSQL};PWD={PASSWORD_DB_HIS_PRODUCTION_FPT_MSSQL}"


# CACHE - REDIS
HOST_REDIS_DEFAULT = os.environ.get("HOST_REDIS_DEFAULT")
PORT_REDIS_DEFAULT = os.environ.get("PORT_REDIS_DEFAULT")

# Applications
CLIENT_ID = os.environ.get("CLIENT_ID")
CLIENT_SECRET = os.environ.get("CLIENT_SECRET")

FORM_TOKEN = os.environ.get("FORM_TOKEN")

# ACCESS_TOKEN_EXPIRE_SECONDS
ACCESS_TOKEN_EXPIRE_SECONDS = int(
    eval(os.environ.get("ACCESS_TOKEN_EXPIRE_SECONDS")))
ACCESS_TOKEN_EXPIRE_REFRESH_SECONDS = int(
    eval(os.environ.get("ACCESS_TOKEN_EXPIRE_REFRESH_SECONDS"))
)

# AUTHORIZATION KEY
KEY_AUTHORIZATION = os.environ.get("KEY_AUTHORIZATION")

# REDMAIL OUTLOOK
USER_REDMAIL = os.environ.get("USER_REDMAIL")
PASSWORD_REDMAIL = os.environ.get("PASSWORD_REDMAIL")

USER_REDMAIL_RECEPTION = os.environ.get("USER_REDMAIL_RECEPTION")
PASSWORD_REDMAIL_RECEPTION = os.environ.get("PASSWORD_REDMAIL_RECEPTION")

# DEBUG_MODE
DEBUG_MODE = os.environ.get("DEBUG_MODE", "0") == "1"

# DATA_UPLOAD_MAX_MEMORY_SIZE
DATA_UPLOAD_MAX_MEMORY_SIZE = int(
    eval(os.environ.get("DATA_UPLOAD_MAX_MEMORY_SIZE", "5242880")))
